import type { Metadata } from "next";
import { Geist, Inter, Poppins, Public_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "500", "400", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const geist = Geist({
  variable: "--font-gesit",
  weight: ["100", "200", "300", "500", "400", "600", "700", "800", "900"],
  subsets: ["latin"],
});
const public_sans = Public_Sans({
  variable: "--font-public_sans",
  weight: ["100", "200", "300", "500", "400", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600"],
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${geist.variable} ${public_sans.variable} ${poppins.variable} antialiased bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
